version: "3"
services:
  watchtower:
    image: "centurylink/watchtower"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup awix-api-production awix-api-development awix-biz-production awix-biz-development awix-production awix-development clubnika-api-production clubnika-api-development clubnika-frontend-production clubnika-frontend-development
    networks:
      nwk:
        ipv4_address: 10.5.0.2

  caddy:
    image: "abiosoft/caddy"
    restart: always
    environment:
      CADDYPATH: "/etc/caddycerts"
    volumes:
      - ./caddy/${CADDY_FILE}:/etc/Caddyfile:ro
      - ~/volumes/caddycerts:/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    networks:
      nwk:
        ipv4_address: 10.5.0.3

  postgres:
    image: "misticwonder/postgres"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ~/volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      nwk:
        ipv4_address: 10.5.0.4

  awix-api-production:
    image: "misticwonder/awix-api-production"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    networks:
      nwk:
        ipv4_address: 10.5.0.5

  awix-api-development:
    image: "misticwonder/awix-api-development"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    networks:
      nwk:
        ipv4_address: 10.5.0.6

  awix-biz-production:
    image: "misticwonder/awix-biz-production"
    restart: always
    depends_on:
      - awix-api-production
    networks:
      nwk:
        ipv4_address: 10.5.0.7

  awix-biz-development:
    image: "misticwonder/awix-biz-development"
    restart: always
    depends_on:
      - awix-api-development
    networks:
      nwk:
        ipv4_address: 10.5.0.8

  awix-production:
    image: "misticwonder/awix-production"
    restart: always
    depends_on:
      - awix-api-production
    networks:
      nwk:
        ipv4_address: 10.5.0.9

  awix-development:
    image: "misticwonder/awix-development"
    restart: always
    depends_on:
      - awix-api-development
    networks:
      nwk:
        ipv4_address: 10.5.0.10





  clubnika-api-production:
    image: "misticwonder/clubnika-api-production"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    networks:
      nwk:
        ipv4_address: 10.5.0.11

  clubnika-api-development:
    image: "misticwonder/clubnika-api-development"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    networks:
      nwk:
        ipv4_address: 10.5.0.12

  clubnika-frontend-production:
    image: "misticwonder/clubnika-frontend-production"
    restart: always
    depends_on:
      - clubnika-api-production
    networks:
      nwk:
        ipv4_address: 10.5.0.13

  clubnika-frontend-development:
    image: "misticwonder/clubnika-frontend-development"
    restart: always
    depends_on:
      - clubnika-api-development
    networks:
      nwk:
        ipv4_address: 10.5.0.14

networks:
  nwk:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.5.0.0/16
